server:
  port: "8080"
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 60s

db:
  host: "postgres"
  port: "5432"
  username: "postgres"
  dbname: "postgres"
  sslmode: "disable"
